apiVersion: v1
kind: Pod
metadata:
  name: mynginx-pod
  labels:
    app: myapp
    type: web-server
spec:
  containers:
    - name: nginx-container
      image: nginx
      resources:
        requests:
          memory: "1Gi"
          cpu: 1
        limits:
          memory: "2Gi"
          cpu: 2
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "dev"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: size
              operator: In
              values: 
              - Large