apiVersion: v1
kind: ReplicationController
metadata:
  name: replicacontroller-nginx
spec:
  replicas: 3
  selector:
    app: replicacontroller-nginx
  template:
    metadata:
      name: nginx-template
      labels:
        app: replicacontroller-nginx
    spec:
      containers:
        - name: replica-pods
          image: nginx
          ports:
            - containerPort: 80
