apiVersion: v1
kind: ReplicationController
metadata:
  name: replicacontroller-nginx
spec:
  
  replicas: 3
  selector:
    app: replicacontroller-nginx
  template:
    metadata:
      name: nginx-template
      labels:
        app: replicacontroller-nginx
    spec:
      containers:
        - name: replica-pods
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "1Gi"
              cpu: 1
          limits:
            memory: "2Gi"
            cpu: 2