apiVersion: v1
kind: ReplicationController
metadata:
  name: my-nginx-replica
spec:
  replicas: 3
  selector:
    app: front-end
  template:
    metadata:
      name: mynginx-app
      labels:
        app: front-end
    spec:
      containers:
        - name: mynginx-cont
          image: nginx
          ports:
            - containerPort: 80